--create table universities
create table if not exists universities(
id integer primary key generated by default as identity,
denomination text not null check (denomination<> ''),
description text,
uri text,
uri_red text
);

--create table teachingmethods
create table if not exists teachingmethods(
id integer primary key generated by default as identity,
denomination text not null check (denomination <> ''),
description text,
uri text,
uri_ac_uk text
);

--create table teachers
create table if not exists teachers(
id integer primary key generated by default as identity,
name text not null check (name <> ''),
username text,
uri text
);

--create table subjects
create table if not exists subjects(
id integer primary key generated by default as identity,
denomination text not null check (denomination <> ''),
description text,
code_acm_ccs text,
uci_uri text,
ou_cso_uri text
);

--create table students
create table if not exists students(
id integer primary key generated by default as identity,
name text not null check (name<> ''),
username varchar,
faculty varchar,
uri text
);

--create table rooms
create table if not exists rooms(
id integer primary key generated by default as identity,
denomination text not null check (denomination <> ''),
description text,
uri text
);

--create table materials
create table if not exists materials(
id integer primary key generated by default as identity,
denomination text not null check (denomination <> ''),
description text,
uri text,
extension text,
dir text
);

--create table languages
create table if not exists languages(
id integer primary key generated by default as identity,
denomination text not null check (denomination<> ''),
description text,
uri text
);

--create table faculties
create table if not exists faculties(
id integer primary key generated by default as identity,
denomination text not null check (denomination <> ''),
description text,
uri text
);

--create table departments
create table if not exists departments(
id integer primary key generated by default as identity,
denomination text not null check (denomination<> ''),
description text,
uri text
);

--create table buildings
create table if not exists buildings(
id integer primary key generated by default as identity,
denomination text not null check (denomination<> ''),
description text,
uri text
);

--create table assessmentmethods
create table if not exists assessmentmethods(
id integer primary key generated by default as identity,
denomination text not null check (denomination<> ''),
description text,
uri text
);

--create table academicterms
create table if not exists academicterms(
id integer primary key generated by default as identity,
denomination text not null check (denomination<> ''),
description text,
uci_uri text
);

--create table courses
create table if not exists courses(
id integer primary key generated by default as identity,
denomination text not null check (denomination <> ''),
description text,
numberofcredits integer,
level varchar,
weeklyhours integer,
startdate date,
enddate date,
languageid integer references languages(id),
subjectid integer references subjects(id),
universityid integer references universities(id),
facultyid integer references faculties(id),
departmentid integer references departments(id),
teachingmethodid integer references teachingmethods(id),
buildingid integer references buildings(id),
roomid integer references rooms(id),
lonposition numeric,
latPosition numeric,
country text,
assessmentmethodid integer references assessmentmethods(id),
uri text,
teachinglevel varchar,
license text
);

--create table courses_teachers
create table if not exists courses_teachers(
id integer primary key generated by default as identity,
courseid integer references courses(id),
teacherid integer references teachers(id)
);

--create table courses_materials
create table if not exists courses_materials(
    id integer primary key generated by default as identity,
    courseid integer references courses(id),
    materialid integer references materials(id)
);

--create table courses_academicterms
create table if not exists courses_academicterms(
id integer primary key generated by default as identity,
courseid integer references courses(id),
academictermid integer references academicterms(id)
);

--create table courses_students
create table if not exists courses_students(
id integer primary key generated by default as identity,
courseid integer references courses(id),
studentid integer references students(id)
);

--Insert into universities
insert into universities(denomination, description,uri, uri_red) values ('University of Informatics Science', 'University of Informatics Science...', 'http://localhost:3000/ld/universities/uci','http://www.uci.cu/');
insert into universities(denomination, description,uri, uri_red) values ('Central University Marta Abreu de Las Villas', 'Central University Marta Abreu de Las Villas...', 'http://localhost:3000/ld/universities/ucl','https://www.uclv.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Havana', 'University of Havana...', 'http://localhost:3000/ld/universities/uh','http://www.uh.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University Center Jose Antonio Echeverria', 'University Center Jose Antonio Echeverria...', 'http://localhost:3000/ld/universities/cujae','https://cujae.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('Eastern University', 'Eastern University...', 'http://localhost:3000/ld/universities/uo','https://www.uo.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Pinar del Rio', 'University of Pinar del Rio...', 'http://localhost:3000/ld/universities/upr', 'http://www.upr.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Isla de la Juventud', 'University of Isla de la Juventud...', 'http://localhost:3000/ld/universities/uij', 'https://www.uij.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Artemisa', 'University of Artemisa...', 'http://localhost:3000/ld/universities/ua', 'http://intranet.uart.edu.cu');
insert into universities(denomination, description,uri, uri_red) values ('University of Matanzas', 'University of Matanzas...', 'http://localhost:3000/ld/universities/umcc', 'http://intranet.umcc.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Santi Spiritus', 'University of Santi Spiritus...', 'http://localhost:3000/ld/universities/uniss', 'https://www.uniss.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Cienfuegos', 'University of Cienfuegos...', 'http://localhost:3000/ld/universities/ucf', 'https://www.ucf.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Ciego de Avila', 'University of Ciego de Avila...', 'http://localhost:3000/ld/universities/unica', 'http://www.unica.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Camaguey', 'University of Camaguey...', 'http://localhost:3000/ld/universities/uc', 'https://www.reduc.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of las Tunas', 'University of las Tunas...', 'http://localhost:3000/ld/universities/ult', 'http://www.ult.edu.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Granma', 'University of Granma...', 'http://localhost:3000/ld/universities/udg', 'https://www.udg.co.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Guantanamo', 'University of Guantanamo...', 'http://localhost:3000/ld/universities/cug', 'http://www.cug.co.cu/');
insert into universities(denomination, description,uri, uri_red) values ('University of Holguin', 'University of Holguin...', 'http://localhost:3000/ld/universities/uho', 'http://www.uho.edu.cu/');

--Insert into teachingmethods
insert into teachingmethods(denomination, description,uri, uri_ac_uk) values ('Teaching large groups', 'Consider ways to make your lectures more impactful and engaging.', 'http://localhost:3000/ld/teachingmethods/tlg','https://www2.le.ac.uk/offices/lli/developing-learning-and-teaching/enhance/strategies/large-groups');
insert into teachingmethods(denomination, description,uri, uri_ac_uk) values ('Small group teaching', 'Explore the facilitator skills required and how to avoid potentially difficult scenarios when students are working in small groups.', 'http://localhost:3000/ld/teachingmethods/sgt','https://www2.le.ac.uk/offices/lli/developing-learning-and-teaching/enhance/strategies/small-group');
insert into teachingmethods(denomination, description,uri, uri_ac_uk) values ('Demonstrating in practical classes', 'Explore the key learning aims of practical classes and how to get learners to effectively engage with them.', 'http://localhost:3000/ld/teachingmethods/dpc','https://www2.le.ac.uk/offices/lli/developing-learning-and-teaching/enhance/strategies/practical');

--Insert into teachers
insert into teachers(name, username,uri) values ('Ivan Perez Mallea', 'mallea', 'http://localhost:3000/ld/teachers/mallea');
insert into teachers(name, username,uri) values ('Febe Angel Ciudad Ricardo', 'fciudad', 'http://localhost:3000/ld/teachers/fciudad');
insert into teachers(name, username,uri) values ('Vivian Estrada Senti', 'vivian', 'http://localhost:3000/ld/teachers/vivian');
insert into teachers(name, username,uri) values ('Ailec Granda Dihigo', 'agranda', 'http://localhost:3000/ld/teachers/agranda');
insert into teachers(name, username,uri) values ('Pedro Yobanis Pineiro Perez', 'ppp', 'http://localhost:3000/ld/teachers/ppp');
insert into teachers(name, username,uri) values ('Surayne Torres Lopez', 'storres', 'http://localhost:3000/ld/teachers/storres');
insert into teachers(name, username,uri) values ('Nayma Martin Amaro', 'nayma', 'http://localhost:3000/ld/teachers/nayma');
insert into teachers(name, username,uri) values ('Iliana Perez Pupo', 'iperez', 'http://localhost:3000/ld/teachers/iperez');
insert into teachers(name, username,uri) values ('Ivonne Burguet Lago', 'iburguet', 'http://localhost:3000/ld/teachers/iburguet');
insert into teachers(name, username,uri) values ('Beatriz Aragon Fernandez', 'beatriz', 'http://localhost:3000/ld/teachers/beatriz');
insert into teachers(name, username,uri) values ('Sandy Diaz', 'sdiaz', 'http://localhost:3000/ld/teachers/sdiaz');
insert into teachers(name, username,uri) values ('Juan Antonio Plasencia Soler', 'juanps', 'http://localhost:3000/ld/teachers/juanps');
insert into teachers(name, username,uri) values ('Fernando Marrero Delgado', 'fernandomd', 'http://localhost:3000/ld/teachers/fernandomd');
insert into teachers(name, username,uri) values ('Yaimi Trujillo Castanola', 'yaimi', 'http://localhost:3000/ld/teachers/yaimi');
insert into teachers(name, username,uri) values ('Aymara Marin Diaz', 'amarin', 'http://localhost:3000/ld/teachers/amarin');
insert into teachers(name, username,uri) values ('Ismaila Sotolongo', 'isotolongo', 'http://localhost:3000/ld/teachers/isotolongo');
insert into teachers(name, username,uri) values ('Odiel Estrada Molina', 'oestrada', 'http://localhost:3000/ld/teachers/oestrada');
insert into teachers(name, username,uri) values ('Dieter Reynaldo Fuentes Cancell', 'dieter', 'http://localhost:3000/ld/teachers/dieter');
insert into teachers(name, username,uri) values ('Ivonne de la Caridad Collada Pena', 'yvonne', 'http://localhost:3000/ld/teachers/yvonne');
insert into teachers(name, username,uri) values ('Pedro Castro Alvarez', 'pcastro', 'http://localhost:3000/ld/teachers/pcastro');
insert into teachers(name, username,uri) values ('Marisol Patterson Pena', 'marisol', 'http://localhost:3000/ld/teachers/marisol');
insert into teachers(name, username,uri) values ('Matilde Leonor Patterson Pena', 'matildelpp', 'http://localhost:3000/ld/teachers/matildelpp');
insert into teachers(name, username,uri) values ('Yadira Ramirez Rodriguez', 'yramirezr', 'http://localhost:3000/ld/teachers/yramirezr');
insert into teachers(name, username,uri) values ('Omar Correa Madrigal', 'ocorrea', 'http://localhost:3000/ld/teachers/ocorrea');
insert into teachers(name, username,uri) values ('Yaniel Lazaro Aragon Barreda', 'yaniell', 'http://localhost:3000/ld/teachers/yaniell');
insert into teachers(name, username,uri) values ('Yaili Ledea Velazquez', 'yledea', 'http://localhost:3000/ld/teachers/yledea');
insert into teachers(name, username,uri) values ('Dunia Castillo Cedeno', 'dcolome', 'http://localhost:3000/ld/teachers/dcolome');
insert into teachers(name, username,uri) values ('Arianna Argelia Gonzalez Santos', 'ariannaags', 'http://localhost:3000/ld/teachers/ariannaags');
insert into teachers(name, username,uri) values ('Lissette Valdes Garcia', 'lvaldesg', 'http://localhost:3000/ld/teachers/lvaldesg');
insert into teachers(name, username,uri) values ('Henry Raul Gonzalez Brito', 'henryraul', 'http://localhost:3000/ld/teachers/henryraul');
insert into teachers(name, username,uri) values ('Walter Baluja Garcia', 'walterb', 'http://localhost:3000/ld/teachers/walterb');
insert into teachers(name, username,uri) values ('Raydel Montesino Perurena', 'raydelmp', 'http://localhost:3000/ld/teachers/raydelmp');
insert into teachers(name, username,uri) values ('Dainys Gainza Reyes', 'dgainza', 'http://localhost:3000/ld/teachers/dgainza');
insert into teachers(name, username,uri) values ('Angel Alberto Vazquez Sanchez', 'aavazquez', 'http://localhost:3000/ld/teachers/aavazquez');
insert into teachers(name, username,uri) values ('Orlando Gabril Toledano Lopez', 'ogtoledano', 'http://localhost:3000/ld/teachers/ogtoledano');
insert into teachers(name, username,uri) values ('Hector Raul Gonzalez Diez', 'hglez', 'http://localhost:3000/ld/teachers/hglez');
insert into teachers(name, username,uri) values ('Osviel Rodriguez Valdes', 'osviel', 'http://localhost:3000/ld/teachers/osviel');
insert into teachers(name, username,uri) values ('Oristela Cuellar Justi', 'oristelacj', 'http://localhost:3000/ld/teachers/oristelacj');
insert into teachers(name, username,uri) values ('Jairo Rojas Delgado', 'jrdelgado', 'http://localhost:3000/ld/teachers/jrdelgado');
insert into teachers(name, username,uri) values ('Gerdys Ernesto Jimenez Moya', 'gejimenez', 'http://localhost:3000/ld/teachers/gejimenez');
insert into teachers(name, username,uri) values ('Yeleny Zulueta Veliz', 'yeleny', 'http://localhost:3000/ld/teachers/yeleny');
insert into teachers(name, username,uri) values ('Rosa Maria Marin Rodriguez', 'rmmarin', 'http://localhost:3000/ld/teachers/rmmarin');


--Insert into subjects
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('educational informatics', 'educational informatics', 'K.3.2', 'http://localhost:3000/ld/subjects/educational_informatics','https://cso.kmi.open.ac.uk/topics/e-learning_system');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('knowledge management ', 'knowledge management', 'K.6.1', 'http://localhost:3000/ld/subjects/knowledge_management','https://cso.kmi.open.ac.uk/topics/engineering_research');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('business management ', 'business management', 'K.1', 'http://localhost:3000/ld/subjects/business_management','https://cso.kmi.open.ac.uk/topics/enterprise_architecture');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('software_quality', 'software_quality', 'D.2.4', 'http://localhost:3000/ld/subjects/software_quality','https://cso.kmi.open.ac.uk/topics/quality_of_softwares');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('english teaching', 'english teaching', 'K.7.3', 'http://localhost:3000/ld/subjects/english_teaching','https://cso.kmi.open.ac.uk/topics/english_teaching');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('video games', 'video games', 'H.4.2', 'http://localhost:3000/ld/subjects/video_games','https://cso.kmi.open.ac.uk/topics/game_development');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('postgres', 'postgres', 'H.2.3', 'http://localhost:3000/ld/subjects/postgres','https://cso.kmi.open.ac.uk/topics/database_management');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('web positioning ', 'web positioning ', 'J.1', 'http://localhost:3000/ld/subjects/web_positioning','https://cso.kmi.open.ac.uk/topics/web_information_extraction');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('cybersecurity', 'cybersecurity', 'C.2.6', 'http://localhost:3000/ld/subjects/cybersecurity','https://cso.kmi.open.ac.uk/topics/security_attacks');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('big data', 'big data', 'I', 'http://localhost:3000/ld/subjects/big_data','https://cso.kmi.open.ac.uk/topics/big_data');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('cryptography', 'cryptography', '', 'http://localhost:3000/ld/subjects/cryptography','');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('neural network', 'neural network', 'I.2', 'http://localhost:3000/ld/subjects/neural_network','https://cso.kmi.open.ac.uk/topics/artificial_neural_network_models');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('word computing', 'word computing', 'I.2', 'http://localhost:3000/ld/subjects/word_computing','https://cso.kmi.open.ac.uk/topics/computing_with_words');
insert into subjects(denomination, description,code_acm_ccs,uci_uri, ou_cso_uri) values ('artificial intelligence', 'artificial intelligence', 'I.2', 'https://localhost:3000/ld/subjects/artificial_intelligence','https://cso.kmi.open.ac.uk/topics/artificial_intelligence');

--Insert into students
insert into students(name, username,faculty, uri) values ('Ana Marys Garcia Rodriguez', 'agarcia', 'Faculty3','http://localhost:3000/ld/teachers/agarcia');
insert into students(name, username,faculty, uri) values ('Alejandro Perdomo Vergara', 'apvergara', 'Faculty3','http://localhost:3000/ld/teachers/apvergara');
insert into students(name, username,faculty, uri) values ('Enier Alarcon Barban ', 'barban', 'Faculty3','http://localhost:3000/ld/teachers/barban');
insert into students(name, username,faculty, uri) values ('Carlos Amador Puentes Cruz', 'carlospc', 'Faculty3','http://localhost:3000/ld/teachers/carlospc');
insert into students(name, username,faculty, uri) values ('Claudia Rojas Maxan', 'crojas', 'Faculty3','http://localhost:3000/ld/teachers/crojas');
insert into students(name, username,faculty, uri) values ('David Alejandro Martinez Perez', 'dmartinezp', 'Faculty3','http://localhost:3000/ld/teachers/dmartinezp');
insert into students(name, username,faculty, uri) values ('Guillermo Manuel Negrin Ortiz', 'gmnegrin', 'Faculty3','http://localhost:3000/ld/teachers/gmnegrin');
insert into students(name, username,faculty, uri) values ('Handy Hernandez Dalmau', 'hdalmau', 'Faculty3','http://localhost:3000/ld/teachers/hdalmau');
insert into students(name, username,faculty, uri) values ('Josue Rivera Riquenes', 'jrivera', 'Faculty3','http://localhost:3000/ld/teachers/jrivera');
insert into students(name, username,faculty, uri) values ('Miguel Autberto Jimenez Benzol ', 'majimenez', 'Faculty3','http://localhost:3000/ld/teachers/majimenez');
insert into students(name, username,faculty, uri) values ('Marieta Pena Abreu', 'mpabreu', 'Faculty3','http://localhost:3000/ld/teachers/mpabreu');
insert into students(name, username,faculty, uri) values ('Pedro Arango Astorga', 'parango', 'Faculty3','http://localhost:3000/ld/teachers/parango');
insert into students(name, username,faculty, uri) values ('Yoan Antonio Lopez Rodriguez', 'yalopez', 'Faculty3','http://localhost:3000/ld/teachers/yalopez');
insert into students(name, username,faculty, uri) values ('Yarina Amoroso Fernandez', 'yarina', 'Faculty3','http://localhost:3000/ld/teachers/yarina');
insert into students(name, username,faculty, uri) values ('Yadian Guillermo Perez Betancourt', 'ygbetancourt', 'Faculty3','http://localhost:3000/ld/teachers/ygbetancourt');
insert into students(name, username,faculty, uri) values ('Yadira Garcia Garcia', 'yggarcia', 'Faculty3','http://localhost:3000/ld/teachers/yggarcia');
insert into students(name, username,faculty, uri) values ('Yusniel Hidalgo Delgado', 'yhdelgado', 'Faculty3','http://localhost:3000/ld/teachers/yhdelgado');
insert into students(name, username,faculty, uri) values ('Aldis Joan Abreu Medina ', 'ajabreu', 'Faculty3','http://localhost:3000/ld/teachers/ajabreu');
insert into students(name, username,faculty, uri) values ('Carlos Manuel Santana Suarez', 'carlos', 'Faculty3','http://localhost:3000/ld/teachers/carlos');
insert into students(name, username,faculty, uri) values ('Gaspar Melchor Gonzalez Font', 'gasparm', 'Faculty3','http://localhost:3000/ld/teachers/gasparm');
insert into students(name, username,faculty, uri) values ('Karelys Borges Beato', 'sylerak', 'Faculty3','http://localhost:3000/ld/teachers/sylerak');

--insert into rooms
insert into rooms(denomination, description,uri) values ('classroom02101', 'classromm', 'http://localhost:3000/ld/rooms/classroom02101');
insert into rooms(denomination, description,uri) values ('classroom02102', 'classromm', 'http://localhost:3000/ld/rooms/classroom02102');
insert into rooms(denomination, description,uri) values ('classroom02103', 'classromm', 'http://localhost:3000/ld/rooms/classroom02103');
insert into rooms(denomination, description,uri) values ('classroom02104', 'classromm', 'http://localhost:3000/ld/rooms/classroom02104');
insert into rooms(denomination, description,uri) values ('classroom02105', 'classromm', 'http://localhost:3000/ld/rooms/classroom02105');
insert into rooms(denomination, description,uri) values ('classroom02106', 'classromm', 'http://localhost:3000/ld/rooms/classroom02106');
insert into rooms(denomination, description,uri) values ('classroom02107', 'classromm', 'http://localhost:3000/ld/rooms/classroom02107');
insert into rooms(denomination, description,uri) values ('classroom02201', 'classromm', 'http://localhost:3000/ld/rooms/classroom02201');
insert into rooms(denomination, description,uri) values ('classroom02202', 'classromm', 'http://localhost:3000/ld/rooms/classroom02202');
insert into rooms(denomination, description,uri) values ('classroom02203', 'classromm', 'http://localhost:3000/ld/rooms/classroom02203');
insert into rooms(denomination, description,uri) values ('classroom02204', 'classromm', 'http://localhost:3000/ld/rooms/classroom02204');
insert into rooms(denomination, description,uri) values ('classroom02205', 'classromm', 'http://localhost:3000/ld/rooms/classroom02205');
insert into rooms(denomination, description,uri) values ('classroom02206', 'classromm', 'http://localhost:3000/ld/rooms/classroom02206');
insert into rooms(denomination, description,uri) values ('classroom02207', 'classromm', 'http://localhost:3000/ld/rooms/classroom02207');
insert into rooms(denomination, description,uri) values ('classroom02301', 'classromm', 'http://localhost:3000/ld/rooms/classroom02301');
insert into rooms(denomination, description,uri) values ('classroom02302', 'classromm', 'http://localhost:3000/ld/rooms/classroom02302');
insert into rooms(denomination, description,uri) values ('classroom02303', 'classromm', 'http://localhost:3000/ld/rooms/classroom02303');
insert into rooms(denomination, description,uri) values ('classroom02304', 'classromm', 'http://localhost:3000/ld/rooms/classroom02304');
insert into rooms(denomination, description,uri) values ('classroom02305', 'classromm', 'http://localhost:3000/ld/rooms/classroom02305');
insert into rooms(denomination, description,uri) values ('classroom02306', 'classromm', 'http://localhost:3000/ld/rooms/classroom02306');
insert into rooms(denomination, description,uri) values ('classroom02307', 'classromm', 'http://localhost:3000/ld/rooms/classroom02307');
insert into rooms(denomination, description,uri) values ('hall02401', 'hall', 'http://localhost:3000/ld/rooms/hall02401');
insert into rooms(denomination, description,uri) values ('hall02402', 'hall', 'http://localhost:3000/ld/rooms/hall02402');
insert into rooms(denomination, description,uri) values ('hall02403', 'hall', 'http://localhost:3000/ld/rooms/hall02403');
insert into rooms(denomination, description,uri) values ('hall02404', 'hall', 'http://localhost:3000/ld/rooms/hall02404');
insert into rooms(denomination, description,uri) values ('hall02405', 'hall', 'http://localhost:3000/ld/rooms/hall02405');
insert into rooms(denomination, description,uri) values ('lab02101', 'lab', 'http://localhost:3000/ld/rooms/lab02101');
insert into rooms(denomination, description,uri) values ('lab02102', 'lab', 'http://localhost:3000/ld/rooms/lab02102');
insert into rooms(denomination, description,uri) values ('lab02103', 'lab', 'http://localhost:3000/ld/rooms/lab02103');
insert into rooms(denomination, description,uri) values ('lab02104', 'lab', 'http://localhost:3000/ld/rooms/lab02104');
insert into rooms(denomination, description,uri) values ('lab02105', 'lab', 'http://localhost:3000/ld/rooms/lab02105');
insert into rooms(denomination, description,uri) values ('lab02106', 'lab', 'http://localhost:3000/ld/rooms/lab02106');
insert into rooms(denomination, description,uri) values ('lab02107', 'lab', 'http://localhost:3000/ld/rooms/lab02107');
insert into rooms(denomination, description,uri) values ('lab02201', 'lab', 'http://localhost:3000/ld/rooms/lab02201');
insert into rooms(denomination, description,uri) values ('lab02202', 'lab', 'http://localhost:3000/ld/rooms/lab02202');
insert into rooms(denomination, description,uri) values ('lab02203', 'lab', 'http://localhost:3000/ld/rooms/lab02203');
insert into rooms(denomination, description,uri) values ('lab02204', 'lab', 'http://localhost:3000/ld/rooms/lab02204');
insert into rooms(denomination, description,uri) values ('lab02205', 'lab', 'http://localhost:3000/ld/rooms/lab02205');
insert into rooms(denomination, description,uri) values ('lab02206', 'lab', 'http://localhost:3000/ld/rooms/lab02206');
insert into rooms(denomination, description,uri) values ('lab02207', 'lab', 'http://localhost:3000/ld/rooms/lab02207');
insert into rooms(denomination, description,uri) values ('lab02301', 'lab', 'http://localhost:3000/ld/rooms/lab02301');
insert into rooms(denomination, description,uri) values ('lab02302', 'lab', 'http://localhost:3000/ld/rooms/lab02302');
insert into rooms(denomination, description,uri) values ('lab02303', 'lab', 'http://localhost:3000/ld/rooms/lab02303');
insert into rooms(denomination, description,uri) values ('lab02304', 'lab', 'http://localhost:3000/ld/rooms/lab02304');
insert into rooms(denomination, description,uri) values ('lab02305', 'lab', 'http://localhost:3000/ld/rooms/lab02305');
insert into rooms(denomination, description,uri) values ('lab02306', 'lab', 'http://localhost:3000/ld/rooms/lab02305');
insert into rooms(denomination, description,uri) values ('lab02307', 'lab', 'http://localhost:3000/ld/rooms/lab02307');

--Insert into materials
insert into materials(denomination, description,uri, extension, dir) values ('Presentation of course 00001', 'Presentation of course 00001', 'http://localhost:3000/ld/materials/courses_materials/course_00001/01','PDF', 'public/courses_materials/Course_00001.pdf');
insert into materials(denomination, description,uri, extension, dir) values ('Presentation of course 00002', 'Presentation of course 00002', 'http://localhost:3000/ld/materials/courses_materials/course_00002/01','PDF','public/courses_materials/Course_00002.pdf');
insert into materials(denomination, description,uri, extension, dir) values ('Presentation of course 00003', 'Presentation of course 00003', 'http://localhost:3000/ld/materials/courses_materials/course_00003/01','PDF', 'public/courses_materials/Course_00003.pdf');
insert into materials(denomination, description,uri, extension, dir) values ('Presentation of course 00004', 'Presentation of course 00004', 'http://localhost:3000/ld/materials/courses_materials/course_00004/01','PDF', 'public/courses_materials/Course_00004.pdf');
insert into materials(denomination, description,uri, extension, dir) values ('Presentation of course 00005', 'Presentation of course 00005', 'http://localhost:3000/ld/materials/courses_materials/course_00005/01','PDF', 'public/courses_materials/Course_00005.pdf');
insert into materials(denomination, description,uri, extension, dir) values ('Presentation of course 00006', 'Presentation of course 00006', 'http://localhost:3000/ld/materials/courses_materials/course_00006/01','PDF', 'public/courses_materials/Course_00006.pdf');
insert into materials(denomination, description,uri, extension, dir) values ('Presentation of course 00007', 'Presentation of course 00007', 'http://localhost:3000/ld/materials/courses_materials/course_00007/01','PDF', 'public/courses_materials/Course_00007.pdf');
insert into materials(denomination, description,uri, extension, dir) values ('Presentation of course 00008', 'Presentation of course 00008', 'http://localhost:3000/ld/materials/courses_materials/course_00008/01','PDF', 'public/courses_materials/Course_00008.pdf');

--Insert into languages
insert into languages(denomination, description,uri) values ('spanish', 'spanish | castilian', 'http://id.loc.gov/vocabulary/iso639-1/es');
insert into languages(denomination, description,uri) values ('english', 'english', 'http://id.loc.gov/vocabulary/iso639-1/en');

--Insert into faculties
insert into faculties(denomination, description,uri) values ('Faculty1', 'Faculty1', 'http://localhost:3000/ld/faculties/Faculty1');
insert into faculties(denomination, description,uri) values ('Faculty2', 'Faculty2', 'http://localhost:3000/ld/faculties/Faculty2');
insert into faculties(denomination, description,uri) values ('Faculty3', 'Faculty3', 'http://localhost:3000/ld/faculties/Faculty3');
insert into faculties(denomination, description,uri) values ('Faculty4', 'Faculty4', 'http://localhost:3000/ld/faculties/Faculty4');
insert into faculties(denomination, description,uri) values ('ciencias y tecnologias educacionales', 'ciencias y tecnologias educacionales', 'http://localhost:3000/ld/faculties/cte');
insert into faculties(denomination, description,uri) values ('facultad introductoria de las ciencias informaticas', 'facultad introductoria de las ciencias informaticas (fici)', 'http://localhost:3000/ld/faculties/fici');

--Insert into departments
insert into departments(denomination, description,uri) values ('Deparment of Informatics', 'Deparment of Informatics (F3Informatics)', 'http://localhost:3000/ld/departments/F3Informatics');
insert into departments(denomination, description,uri) values ('Deparment of Math', 'Deparment of Math (F3Math)', 'http://localhost:3000/ld/departments/F3Math');
insert into departments(denomination, description,uri) values ('Department of Business Management', 'Department of Business Management (F3BM)', 'http://localhost:3000/ld/departments/F3BM');
insert into departments(denomination, description,uri) values ('Deparment of Informatics', 'Deparment of Informatics (F1Informatics)', 'http://localhost:3000/ld/departments/F1Informatics');
insert into departments(denomination, description,uri) values ('Deparment of Math', 'Deparment of Math (F1Math)', 'http://localhost:3000/ld/departments/F1Math');
insert into departments(denomination, description,uri) values ('Department of Business Management', 'Department of Business Management (F1BM)', 'http://localhost:3000/ld/departments/F1BM');
insert into departments(denomination, description,uri) values ('Deparment of Informatics', 'Deparment of Informatics (F2Informatics)', 'http://localhost:3000/ld/departments/F2Informatics');
insert into departments(denomination, description,uri) values ('Deparment of Math', 'Deparment of Math (F2Math)', 'http://localhost:3000/ld/departments/F2Math');
insert into departments(denomination, description,uri) values ('Department of Business Management', 'Department of Business Management (F2BM)', 'http://localhost:3000/ld/departments/F2BM');
insert into departments(denomination, description,uri) values ('Deparment of Informatics', 'Deparment of Informatics (F3Informatics)', 'http://localhost:3000/ld/departments/F3Informatics');
insert into departments(denomination, description,uri) values ('Deparment of Math', 'Deparment of Math (F3Math)', 'http://localhost:3000/ld/departments/F3Math');
insert into departments(denomination, description,uri) values ('Department of Business Management', 'Department of Business Management (F3BM)', 'http://localhost:3000/ld/departments/F3BM');
insert into departments(denomination, description,uri) values ('Deparment of Informatics', 'Deparment of Informatics (F4Informatics)', 'http://localhost:3000/ld/departments/F4Informatics');
insert into departments(denomination, description,uri) values ('Deparment of Math', 'Deparment of Math (F4Math)', 'http://localhost:3000/ld/departments/F4Math');
insert into departments(denomination, description,uri) values ('Department of Business Management', 'Department of Business Management (F4BM)', 'http://localhost:3000/ld/departments/F4BM');

--Insert into buildings
insert into buildings(denomination, description,uri) values ('building 1', 'building 1 (b1)', 'http://localhost:3000/ld/buildings/b1');
insert into buildings(denomination, description,uri) values ('building 2', 'building 2 (b2)', 'http://localhost:3000/ld/buildings/b2');
insert into buildings(denomination, description,uri) values ('building 3', 'building 3 (b3)/Chinesse', 'http://localhost:3000/ld/buildings/b3');
insert into buildings(denomination, description,uri) values ('building 4', 'building 4 (b4)', 'http://localhost:3000/ld/buildings/b4');
insert into buildings(denomination, description,uri) values ('building 5', 'building 5 (b5)', 'http://localhost:3000/ld/buildings/b5');
insert into buildings(denomination, description,uri) values ('building 6', 'building 6 (b6)', 'http://localhost:3000/ld/buildings/b6');
insert into buildings(denomination, description,uri) values ('rectorate building 1', 'rectorate building 1', 'http://localhost:3000/ld/buildings/rb1');

--Insert into assessmentmethods;
insert into assessmentmethods(denomination, description,uri) values ('Discussion', 'Discussion', 'http://localhost:3000/ld/assessmentmethods/discussion');
insert into assessmentmethods(denomination, description,uri) values ('Exam', 'Exam', 'http://localhost:3000/ld/assessmentmethods/exam');
insert into assessmentmethods(denomination, description,uri) values ('Written assignment', 'Written assignment', 'http://localhost:3000/ld/assessmentmethods/written_assignment');
insert into assessmentmethods(denomination, description,uri) values ('Final/Midterm', 'Final/Midterm', 'http://localhost:3000/ld/assessmentmethods/final_midterm');
insert into assessmentmethods(denomination, description,uri) values ('Experiential Assignment', 'Experiential Assignment', 'http://localhost:3000/ld/assessmentmethods/experiential_assignment');
insert into assessmentmethods(denomination, description,uri) values ('Problem Assignment', 'Problem Assignment', 'http://localhost:3000/ld/assessmentmethods/problem_assignment');
insert into assessmentmethods(denomination, description,uri) values ('Quiz', 'Quiz', 'http://localhost:3000/ld/assessmentmethods/quiz');
insert into assessmentmethods(denomination, description,uri) values ('Paper', 'Paper', 'http://localhost:3000/ld/assessmentmethods/paper');
insert into assessmentmethods(denomination, description,uri) values ('Journal', 'Journal', 'http://localhost:3000/ld/assessmentmethods/journal');
insert into assessmentmethods(denomination, description,uri) values ('Presentation', 'Presentation', 'http://localhost:3000/ld/assessmentmethods/presentation');
insert into assessmentmethods(denomination, description,uri) values ('Pretest', 'Pretest', 'http://localhost:3000/ld/assessmentmethods/pretest');
insert into assessmentmethods(denomination, description,uri) values ('Project', 'Project', 'http://localhost:3000/ld/assessmentmethods/project');
insert into assessmentmethods(denomination, description,uri) values ('Peer Review', 'Peer Review', 'http://localhost:3000/ld/assessmentmethods/peer_review');
insert into assessmentmethods(denomination, description,uri) values ('Form', 'Form', 'http://localhost:3000/ld/assessmentmethods/form');
insert into assessmentmethods(denomination, description,uri) values ('Group Project', 'Group Project', 'http://localhost:3000/ld/assessmentmethods/group_project');


--Insert into academicterms
insert into academicterms(denomination, description,uci_uri) values ('educational informatics', 'educational informatics', 'http://localhost:3000/ld/academicterms/educational_informatics');
insert into academicterms(denomination, description,uci_uri) values ('knowledge management', 'knowledge management', 'http://localhost:3000/ld/academicterms/knowledge_management');
insert into academicterms(denomination, description,uci_uri) values ('business management', 'business management', 'http://localhost:3000/ld/academicterms/business_management');
insert into academicterms(denomination, description,uci_uri) values ('software quality', 'software quality', 'http://localhost:3000/ld/academicterms/software_quality');
insert into academicterms(denomination, description,uci_uri) values ('english teaching', 'english teaching', 'http://localhost:3000/ld/academicterms/english_teaching');
insert into academicterms(denomination, description,uci_uri) values ('video games', 'video games', 'http://localhost:3000/ld/academicterms/video_games');
insert into academicterms(denomination, description,uci_uri) values ('postgres', 'postgres', 'http://localhost:3000/ld/academicterms/postgres');
insert into academicterms(denomination, description,uci_uri) values ('web positioning', 'web positioning', 'http://localhost:3000/ld/academicterms/web_positioning');
insert into academicterms(denomination, description,uci_uri) values ('cybersecurity', 'cybersecurity', 'http://localhost:3000/ld/academicterms/cybersecurity');
insert into academicterms(denomination, description,uci_uri) values ('neural network', 'neural network', 'http://localhost:3000/ld/academicterms/neural_network');
insert into academicterms(denomination, description,uci_uri) values ('word computing', 'word computing', 'http://localhost:3000/ld/academicterms/word_computing');
insert into academicterms(denomination, description,uci_uri) values ('cryptography', 'cryptography', 'http://localhost:3000/ld/academicterms/cryptography');
insert into academicterms(denomination, description,uci_uri) values ('artificial intelligence', 'artificial intelligence', 'https://localhost:3000/ld/academicterms/artificial_intelligence');

--Insert into courses
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate, enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Diseño y produccion de recursos educativos digitales', 'Diseño y produccion de recursos educativos digitales', 2, 'basic', 40,'2020-11-25','2020-12-05',8, 21, 12, 8, 10, 6, 6, 7, 77.7812, 21.5218, 'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00001', 'postgraduate', 'http://creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate, enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Diseño didáctico de Entornos Virtuales de Enseñanza-Aprendizaje','Diseño didáctico de Entornos Virtuales de Enseñanza-Aprendizaje',2,'basic',40,'2020-11-25','2020-12-05',8,21,12,8,10,6,6,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00002','postgraduate','http://creativecommons.org/licenses/by/3.0/');
insert into courses( denomination, description, numberofcredits, level, weeklyhours, startdate, enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Gestion del conocimiento en la red','Gestion del conocimiento en la red',2,'basic',40,'2020-11-25','2020-12-05',8,22,12,8,10,6,6,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00003','postgraduate','http://creativecommons.org/licenses/by/3.0/');
insert into courses( denomination, description, numberofcredits, level, weeklyhours, startdate, enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Buenas prácticas para la investigacion cientifica','Buenas prácticas para la investigacion cientifica',2,'basic',40,'2020-11-25','2020-12-05',8,22,12,9,13,6,7,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00004','postgraduate','http:creativecommons.org/licenses/by/3.0/');  
insert into courses( denomination, description, numberofcredits, level, weeklyhours, startdate, enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Métodos de evaluación de criterios de expertos','Métodos de evaluación de criterios de expertos',2,'basic',40,'2020-11-25','2020-12-05',8,22 ,12,9,13,6,7,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00005','postgraduate','http://creativecommons.org/licenses/by/3.0/');  
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate, enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Introducción al diseño de proyectos con el Enfoque del Marco Lógico','Introducción al diseño de proyectos con el Enfoque del Marco Lógico',2,'basic',40,'2020-11-25','2020-12-05',8,22,12,11,19,6,9,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00006','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate, enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sostenibilidad Corporativa','Sostenibilidad Corporativa', 2, 'basic',40, '2020-11-25', '2020-12-05', 8, 23, 12, 10, 9, 6, 8, 7, 77.7812, 21.5218, 'https://www.geonames.org/countries/CU/cuba.html', 6, 'http://localhost:3000/ld/courses/00007', 'postgraduate', 'http://creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate, enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Aseguramiento de la calidad del proceso y del producto (PPQA)','Aseguramiento de la calidad del proceso y del producto (PPQA)', 2,'basic',40, '2020-11-25', '2020-12-05',8, 24, 12, 10, 7, 6, 8, 7, 77.7812, 21.5218, 'https://www.geonames.org/countries/CU/cuba.html', 6, 'http://localhost:3000/ld/courses/00008', 'postgraduate','http://creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00009','Sintetico 00009', 2,  'basic', 40, '2016-01-10', '2016-01-15', 8, 21,12,8,7, 6, 6, 7,77.7812, 21.5218, 'https://www.geonames.org/countries/CU/cuba.html', 5, 'http://localhost:3000/ld/courses/00009', 'postgraduate', 'http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00010', 'Sintetico 00010',3,'basic', 80, '2016-01-10', '2016-01-22', 8, 22, 12, 9, 8, 6,7,7,77.7812,21.5218, 'https://www.geonames.org/countries/CU/cuba.html',5, 'http://localhost:3000/ld/courses/00010', 'postgraduate', 'http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00011', 'Sintetico 00011', 2, 'basic', 40, '2016-01-10', '2016-01-15', 8, 23, 12, 10, 9, 7, 8, 7, 77.7812, 21.5218, 'https://www.geonames.org/countries/CU/cuba.html', 6,'http://localhost:3000/ld/courses/00011', 'postgraduate','http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00012', 'Sintetico 00012', 3, 'basic', 80, '2016-01-10', '2016-01-22', 9,24, 12, 11, 10,8, 9, 7,77.7812, 21.5218, 'https://www.geonames.org/countries/CU/cuba.html',  5, 'http://localhost:3000/ld/courses/00012', 'postgraduate', 'http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00013','Sintetico 00013',2,'basic',40,'2016-01-10','2016-01-15',8,25,12,12, 11,6,10,7, 77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00013','postgraduate','http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00014','Sintetico 00014',3,'basic',80,'2016-01-10','2016-01-22',8, 26,12,13,12,6,11,7,77.7812,21.5218, 'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00014', 'postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00015','Sintetico 00015',2,'basic',40,'2016-01-10','2016-01-15',8,26,12,8,13,7,12,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html', 5,'http://localhost:3000/ld/courses/00015','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00016','Sintetico 00016',3,'basic',80,'2016-01-10','2016-01-22', 9,27,12,9,14,8,6,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00016','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00017','Sintetico 00017',2,'basic',40,'2016-01-10','2016-01-15', 8, 28,12,10, 15,6,7,7, 77.7812, 21.5218, 'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00017', 'postgraduate', 'http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00018','Sintetico 00018',3,'basic',80,'2016-01-10','2016-01-22',8, 29,12, 11, 16,6,8,7,77.7812, 21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00018', 'postgraduate','http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00019','Sintetico 00019',2,'basic',40,'2016-01-10','2016-01-15', 8,30,12,12,17,7,9,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00019','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00020','Sintetico 00020',3,'basic',80,'2016-01-10','2016-01-22', 8,31,12,13, 18,8,10,7, 77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html', 6,'http://localhost:3000/ld/courses/00020','postgraduate','http:creativecommons.org/licenses/by/3.0/');  
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00021','Sintetico 00021',2,'basic',40,'2016-01-10','2016-01-15', 9, 32,12,8,19 ,6,11,7,77.7812, 21.5218,'https://www.geonames.org/countries/CU/cuba.html', 5,'http://localhost:3000/ld/courses/00021','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00022','Sintetico 00022',3,'basic',80,'2016-01-10','2016-01-22',8, 21,12,9,7 ,6,12,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html', 5,'http://localhost:3000/ld/courses/00022','postgraduate','http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00023','Sintetico 00023',2,'basic',40,'2016-01-10','2016-01-15',8,22,12,10, 8,7,6,7, 77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html', 6,'http://localhost:3000/ld/courses/00023','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00024','Sintetico 00024',3,'basic',80,'2017-01-10','2017-01-22', 8,23,12,11,9,8,7,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00024','postgraduate','http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00025','Sintetico 00025',2,'basic',40,'2017-01-10','2017-01-15',9,24,12,12,10,6,8,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00025','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00026','Sintetico 00026',3,'basic',80,'2017-01-10','2017-01-22',8,25,12,13,11,6,9,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00026','postgraduate','http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00027','Sintetico 00027',2,'basic',40,'2017-01-10','2017-01-15', 8, 26,12, 8,12,7,10,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00027','postgraduate','http:creativecommons.org/licenses/by/3.0/');  
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00028','Sintetico 00028',3,'basic',80,'2017-01-10','2017-01-22', 8,27,12,9, 13,8,11,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00028','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00029','Sintetico 00029',2,'basic',40,'2017-01-10','2017-01-15',9,28,12,10,14,6,12,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00029','postgraduate','http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00030','Sintetico',3,'basic',80,'2017-01-10','2017-01-22',8,29,12,11 ,15,6,6,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00030','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00031','Sintetico 00031',2,'basic',40,'2019-01-10','2019-01-15',8,30,12,12,16,7,7,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00031','postgraduate','http:creativecommons.org/licenses/by/3.0/'); 
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00032','Sintetico 00032',3,'basic',80,'2019-01-10','2019-01-22',8,31,12,13,17,8,8,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00032','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00033','Sintetico 00033',2,'basic',40,'2019-01-10','2019-01-15',9,32,12,8,18,6,9,7,77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',5,'http://localhost:3000/ld/courses/00033','postgraduate','http:creativecommons.org/licenses/by/3.0/');
insert into courses(denomination, description, numberofcredits, level, weeklyhours, startdate,enddate, languageid,subjectid, universityid,facultyid, departmentid, teachingmethodid, buildingid,roomid, lonposition, latposition, country, assessmentmethodid, uri, teachinglevel, license) values ('Sintetico 00035','Sintetico 00035',2,'basic',40,'2019-01-10','2019-01-15', 8, 22,12, 10,7,7,11,7, 77.7812,21.5218,'https://www.geonames.org/countries/CU/cuba.html',6,'http://localhost:3000/ld/courses/00035','postgraduate','http:creativecommons.org/licenses/by/3.0/');


--Insert into courses_teachers
insert into courses_teachers (courseid, teacherid) values (10,12);
insert into courses_teachers (courseid, teacherid) values (11,13);
insert into courses_teachers (courseid, teacherid) values (12,14);
insert into courses_teachers (courseid, teacherid) values (12,15);
insert into courses_teachers (courseid, teacherid) values (13,16);
insert into courses_teachers (courseid, teacherid) values (13,17);
insert into courses_teachers (courseid, teacherid) values (13,18);
insert into courses_teachers (courseid, teacherid) values (13,19);
insert into courses_teachers (courseid, teacherid) values (14,20);
insert into courses_teachers (courseid, teacherid) values (15,21);
insert into courses_teachers (courseid, teacherid) values (15,22);
insert into courses_teachers (courseid, teacherid) values (18,23);
insert into courses_teachers (courseid, teacherid) values (18,24);
insert into courses_teachers (courseid, teacherid) values (19,25);
insert into courses_teachers (courseid, teacherid) values (19,26);
insert into courses_teachers (courseid, teacherid) values (19,27);
insert into courses_teachers (courseid, teacherid) values (20,28);
insert into courses_teachers (courseid, teacherid) values (20,29);
insert into courses_teachers (courseid, teacherid) values (21,30);
insert into courses_teachers (courseid, teacherid) values (21,31);
insert into courses_teachers (courseid, teacherid) values (21,32);
insert into courses_teachers (courseid, teacherid) values (21,33);
insert into courses_teachers (courseid, teacherid) values (22,34);
insert into courses_teachers (courseid, teacherid) values (22,35);
insert into courses_teachers (courseid, teacherid) values (23,36);
insert into courses_teachers (courseid, teacherid) values (23,37);
insert into courses_teachers (courseid, teacherid) values (24,38);
insert into courses_teachers (courseid, teacherid) values (24,39);
insert into courses_teachers (courseid, teacherid) values (24,40);
insert into courses_teachers (courseid, teacherid) values (25,41);
insert into courses_teachers (courseid, teacherid) values (25,42);
insert into courses_teachers (courseid, teacherid) values (25,43);
insert into courses_teachers (courseid, teacherid) values (25,44);
insert into courses_teachers (courseid, teacherid) values (26,45);
insert into courses_teachers (courseid, teacherid) values (26,46);
insert into courses_teachers (courseid, teacherid) values (26,47);
insert into courses_teachers (courseid, teacherid) values (27,48);
insert into courses_teachers (courseid, teacherid) values (27,49);
insert into courses_teachers (courseid, teacherid) values (28,50);
insert into courses_teachers (courseid, teacherid) values (28,51);
insert into courses_teachers (courseid, teacherid) values (29,52);
insert into courses_teachers (courseid, teacherid) values (29,53);


--Insert into courses_materials
insert into courses_materials (courseid, materialid) values(10, 6);
insert into courses_materials (courseid, materialid) values(11, 7);
insert into courses_materials (courseid, materialid) values(12, 8);
insert into courses_materials (courseid, materialid) values(13,9);
insert into courses_materials (courseid, materialid) values(14,10);
insert into courses_materials (courseid, materialid) values(15,11);
insert into courses_materials (courseid, materialid) values(18,12);
insert into courses_materials (courseid, materialid) values(19,13);

--Insert into courses_academicterms
insert into courses_academicterms (courseid, academictermid) values (10,10);
insert into courses_academicterms (courseid, academictermid) values (11,10);
insert into courses_academicterms (courseid, academictermid) values (12,11);
insert into courses_academicterms (courseid, academictermid) values (13,11);
insert into courses_academicterms (courseid, academictermid) values (14,11);
insert into courses_academicterms (courseid, academictermid) values (15,11);
insert into courses_academicterms (courseid, academictermid) values (18,12);
insert into courses_academicterms (courseid, academictermid) values (19,13);

--Insert into courses_students
insert into courses_students (courseid, studentid) values (10,12);
insert into courses_students (courseid, studentid) values (10,13);
insert into courses_students (courseid, studentid) values (10,14);
insert into courses_students (courseid, studentid) values (11, 15);
insert into courses_students (courseid, studentid) values (11, 16);
insert into courses_students (courseid, studentid) values (11, 17);
insert into courses_students (courseid, studentid) values (12, 18);
insert into courses_students (courseid, studentid) values (12, 19);
insert into courses_students (courseid, studentid) values (12, 20);
insert into courses_students (courseid, studentid) values (13,21);
insert into courses_students (courseid, studentid) values (13,22);
insert into courses_students (courseid, studentid) values (13,23);
insert into courses_students (courseid, studentid) values (14,24);
insert into courses_students (courseid, studentid) values (14,25);
insert into courses_students (courseid, studentid) values (14,26);
insert into courses_students (courseid, studentid) values (15,27);
insert into courses_students (courseid, studentid) values (15,28);
insert into courses_students (courseid, studentid) values (15,29);
insert into courses_students (courseid, studentid) values (18,30);
insert into courses_students (courseid, studentid) values (18,31);
insert into courses_students (courseid, studentid) values (19,32);
insert into courses_students (courseid, studentid) values (19,33);